#!/bin/bash
# Guide for setting up the local VM in UTM
# This script prints instructions since UTM VM creation is done via GUI

echo "==========================================="
echo "  UTM VM Setup Guide"
echo "==========================================="
echo ""
echo "Step 1: Download Ubuntu 22.04 ARM64 Server ISO"
echo "  URL: https://cdimage.ubuntu.com/releases/22.04/release/"
echo "  File: ubuntu-22.04.5-live-server-arm64.iso"
echo ""
echo "Step 2: Create VM in UTM"
echo "  - Open UTM app"
echo "  - Click '+' to create a new VM"
echo "  - Select 'Virtualize' (not Emulate)"
echo "  - Choose 'Linux'"
echo "  - Browse to the downloaded ISO"
echo "  - Set Memory: 4096 MB (4 GB)"
echo "  - Set CPU Cores: 4"
echo "  - Set Storage: 20 GB"
echo "  - Finish and start the VM"
echo ""
echo "Step 3: Install Ubuntu"
echo "  - Follow the installer prompts"
echo "  - Create user: vcc (or any username)"
echo "  - Enable OpenSSH server when prompted"
echo ""
echo "Step 4: After installation, shut down the VM"
echo "  - In UTM, right-click the VM > Edit"
echo "  - Remove the CD/DVD drive (or eject the ISO)"
echo "  - Go to Network > Port Forward and add:"
echo "    Host: 2222 -> Guest: 22 (SSH)"
echo "    Host: 5000 -> Guest: 5000 (Flask)"
echo "  - Start the VM again"
echo ""
echo "Step 5: Install dependencies inside the VM"
echo "  ssh -p 2222 vcc@localhost"
echo "  sudo apt update && sudo apt upgrade -y"
echo "  sudo apt install -y python3 python3-pip python3-venv stress-ng"
echo "  pip3 install flask psutil"
echo ""
echo "Step 6: Deploy the app using deploy_to_vm.sh"
echo "==========================================="
